-- V5: Users are created by DataLoader.java at runtime using PasswordEncoder
-- This ensures correct BCrypt encoding of passwords
-- Default credentials:
--   Admin: admin@7eleven.com / Admin@123
--   User:  user@7eleven.com / User@123
