# Application - Docker Profile
spring.datasource.url=jdbc:postgresql://postgres:5432/seveneleven
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.host=redis
spring.data.redis.port=6379

spring.cache.type=simple
spring.cache.redis.time-to-live=300000
spring.cache.redis.enabled=false

jwt.secret=7ElevenVietnam2024SecretKeyForJWTTokenGenerationMustBeAtLeast256Bits
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

cors.allowed-origins=http://localhost:5173,http://localhost:3000

logging.level.com.seveneleven=DEBUG
